// Maps team names (as returned by football-data.org) to flag emojis
const FLAGS: Record<string, string> = {
  // Group A
  "United States": "🇺🇸",
  "Canada": "🇨🇦",
  "Mexico": "🇲🇽",
  "Panama": "🇵🇦",
  "Honduras": "🇭🇳",
  "Uzbekistan": "🇺🇿",

  // Group B
  "Argentina": "🇦🇷",
  "Chile": "🇨🇱",
  "Ecuador": "🇪🇨",
  "Peru": "🇵🇪",
  "Colombia": "🇨🇴",
  "Bolivia": "🇧🇴",
  "Venezuela": "🇻🇪",
  "Paraguay": "🇵🇾",
  "Uruguay": "🇺🇾",

  // Europe
  "Germany": "🇩🇪",
  "France": "🇫🇷",
  "Spain": "🇪🇸",
  "Portugal": "🇵🇹",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Netherlands": "🇳🇱",
  "Belgium": "🇧🇪",
  "Italy": "🇮🇹",
  "Croatia": "🇭🇷",
  "Serbia": "🇷🇸",
  "Switzerland": "🇨🇭",
  "Denmark": "🇩🇰",
  "Austria": "🇦🇹",
  "Poland": "🇵🇱",
  "Ukraine": "🇺🇦",
  "Turkey": "🇹🇷",
  "Czech Republic": "🇨🇿",
  "Slovakia": "🇸🇰",
  "Hungary": "🇭🇺",
  "Romania": "🇷🇴",
  "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "Greece": "🇬🇷",
  "Albania": "🇦🇱",
  "Slovenia": "🇸🇮",
  "Georgia": "🇬🇪",

  // South America
  "Brazil": "🇧🇷",

  // Africa
  "Morocco": "🇲🇦",
  "Senegal": "🇸🇳",
  "Nigeria": "🇳🇬",
  "Cameroon": "🇨🇲",
  "Ghana": "🇬🇭",
  "Egypt": "🇪🇬",
  "Tunisia": "🇹🇳",
  "Algeria": "🇩🇿",
  "Ivory Coast": "🇨🇮",
  "South Africa": "🇿🇦",
  "DR Congo": "🇨🇩",
  "Congo DR": "🇨🇩",
  "Mali": "🇲🇱",
  "Burkina Faso": "🇧🇫",
  "Cape Verde": "🇨🇻",
  "Cape Verde Islands": "🇨🇻",
  "Curaçao": "🇨🇼",
  "Curacao": "🇨🇼",
  "Czechia": "🇨🇿",
  "Angola": "🇦🇴",
  "Tanzania": "🇹🇿",
  "Comoros": "🇰🇲",
  "Sudan": "🇸🇩",
  "Mozambique": "🇲🇿",

  // Asia
  "Japan": "🇯🇵",
  "South Korea": "🇰🇷",
  "Korea Republic": "🇰🇷",
  "Australia": "🇦🇺",
  "Iran": "🇮🇷",
  "Saudi Arabia": "🇸🇦",
  "Qatar": "🇶🇦",
  "Iraq": "🇮🇶",
  "UAE": "🇦🇪",
  "Jordan": "🇯🇴",
  "China PR": "🇨🇳",
  "Oman": "🇴🇲",
  "Bahrain": "🇧🇭",
  "Kuwait": "🇰🇼",
  "Vietnam": "🇻🇳",
  "Indonesia": "🇮🇩",
  "Thailand": "🇹🇭",
  "Philippines": "🇵🇭",
  "Malaysia": "🇲🇾",

  // CONCACAF others
  "Jamaica": "🇯🇲",
  "Costa Rica": "🇨🇷",
  "Guatemala": "🇬🇹",
  "El Salvador": "🇸🇻",
  "Haiti": "🇭🇹",
  "Cuba": "🇨🇺",
  "Trinidad and Tobago": "🇹🇹",

  // Oceania
  "New Zealand": "🇳🇿",
  "Fiji": "🇫🇯",
  "Papua New Guinea": "🇵🇬",

  // Others
  "Sweden": "🇸🇪",
  "Norway": "🇳🇴",
  "Finland": "🇫🇮",
  "Israel": "🇮🇱",
  "Bosnia and Herzegovina": "🇧🇦",
  "Bosnia-Herzegovina": "🇧🇦",
  "North Macedonia": "🇲🇰",
  "Montenegro": "🇲🇪",
  "Kosovo": "🇽🇰",
  "Iceland": "🇮🇸",
  "Luxembourg": "🇱🇺",
  "Kazakhstan": "🇰🇿",
  "Azerbaijan": "🇦🇿",
  "Armenia": "🇦🇲",
}

export function getFlag(teamName: string): string {
  return FLAGS[teamName] ?? "🏳️"
}
